name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Review
        id: ai-review
        uses: freeedcom/ai-codereviewer@v2.7.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4"
          exclude: "**/*.json, **/*.md"

      - name: Add Comment on Failure
        if: ${{ steps.ai-review.outputs.review_result != '{}' }}
        uses: actions/github-script@v4
        id: add-comment
        env:
          FAILURES: ${{ steps.ai-review.outputs.review_result }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log("Failures:", process.env.FAILURES); // Add this line for debugging
            const failures = JSON.parse(process.env.FAILURES || '[]');
            const issueBody = "### AI Code Reviews\n\n";
            failures.forEach(failure => {
              issueBody += `- ${failure}\n`;
            });
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueBody
            });
